//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Xunit;

    public partial class About
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Please enter first name!")]
        [StringLength(10, ErrorMessage = "Please only enter 4-10 length character.", MinimumLength = 4)]
        public string FIRSTNAME { get; set; }
        [Required(ErrorMessage = "Please enter second name!")]
        [StringLength(10, ErrorMessage = "Please only enter 4-10 length character.", MinimumLength = 4)]
        public string SECONDNAME { get; set; }
        [Required(ErrorMessage = "Please enter surname!")]
        [StringLength(10, ErrorMessage = "Please only enter 4-10 length character.", MinimumLength = 4)]
        public string SURNAME { get; set; }
        [Required(ErrorMessage = "Please enter phone number!")]
        [StringLength(10, ErrorMessage = "Please only enter 10 length character.", MinimumLength = 10)]
        public string PHONE { get; set; }
        [Required(ErrorMessage = "Please enter email!")]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Please enter description!")]
        [StringLength(800, ErrorMessage = "Please max enter 800 length character.")]
        public string DESCRIPTION { get; set; }
        [Required(ErrorMessage = "Please choose birthday!")]
        [Column("BIRTHDAY", TypeName = "DateTime2")]
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        [Required(ErrorMessage = "Please enter phone number!")]
        [StringLength(10, ErrorMessage = "Please only enter 4-10 length character.", MinimumLength = 4)]
        public string LOCATION { get; set; }
        [Required(ErrorMessage = "Please enter phone number!")]
        [StringLength(10, ErrorMessage = "Please max enter 10 length character.")]
        public string DRIVINGLICENCE { get; set; }
        [Required(ErrorMessage = "Please enter phone number!")]
        [StringLength(150, ErrorMessage = "Please max enter 150 length character.")]
        public string PHOTO { get; set; }
    }
}
