//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Xunit;

    public partial class About
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Please enter first name!")]
        public string FIRSTNAME { get; set; }
        [Required(ErrorMessage = "Please enter second name!")]
        public string SECONDNAME { get; set; }
        [Required(ErrorMessage = "Please enter surname!")]
        public string SURNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string DESCRIPTION { get; set; }
        public string LOCATION { get; set; }
        public string DRIVINGLICENCE { get; set; }
        public string PHOTO { get; set; }
    }
}
