//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Certificate
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Please enter certificate name!")]
        [StringLength(50, ErrorMessage = "Please only enter 4-50 length character.", MinimumLength = 4)]
        public string NAME { get; set; }
        [Required(ErrorMessage = "Please choose date!")]
        [Column("DATE", TypeName = "DateTime2")]
        public Nullable<System.DateTime> DATE { get; set; }
        [Required(ErrorMessage = "Please enter corporation name!")]
        [StringLength(50, ErrorMessage = "Please only enter 4-50 length character.", MinimumLength = 4)]
        public string CORPORATION { get; set; }
        [Required(ErrorMessage = "Please enter certificate url!")]
        [StringLength(200, ErrorMessage = "Please only enter 4-200 length character.", MinimumLength = 4)]
        public string URL { get; set; }
    }
}
