//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int ID { get; set; }
        //[Required(ErrorMessage="Please enter name!")]
        public string NAME { get; set; }
        //[Required(ErrorMessage = "Please enter mail!")]
        public string MAIL { get; set; }
        //[Required(ErrorMessage = "Please enter phone!")]
        public string PHONE { get; set; }
        //[Required(ErrorMessage = "Please enter message!")]
        public string MESSAGE { get; set; }
        //[Required(ErrorMessage = "Please enter subject!")]
        public string SUBJECT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
