//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Education
    {
        public int ID { get; set; }
        [Required (ErrorMessage ="Uyarý")]
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string FACULTY { get; set; }
        public string SECTION { get; set; }
        public Nullable<System.DateTime> START { get; set; }
        public Nullable<System.DateTime> FINISH { get; set; }
    }
}
