//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Experience
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Please enter position name!")]
        [StringLength(20, ErrorMessage = "Please only enter 4-20 length character.", MinimumLength = 4)]
        public string POSITION { get; set; }
        [Required(ErrorMessage = "Please choose company name!")]
        [StringLength(20, ErrorMessage = "Please only enter 4-20 length character.", MinimumLength = 4)]
        public string COMPANY { get; set; }
        [Required(ErrorMessage = "Please choose sector name!")]
        [StringLength(20, ErrorMessage = "Please only enter 4-20 length character.", MinimumLength = 4)]
        public string SECTOR { get; set; }
        [Required(ErrorMessage = "Please choose start date!")]
        [Column("START", TypeName = "DateTime2")]
        public Nullable<System.DateTime> START { get; set; }
        [Required(ErrorMessage = "Please choose finish date!")]
        [Column("FINISH", TypeName = "DateTime2")]
        public Nullable<System.DateTime> FINISH { get; set; }
        [Required(ErrorMessage = "Please choose way of working!")]
        [StringLength(20, ErrorMessage = "Please only enter 4-20 length character.", MinimumLength = 4)]
        public string WAYOFWORKING { get; set; }
    }
}
