//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Portfolio
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Please enter project name!")]
        [StringLength(30, ErrorMessage = "Please only enter 4-30 length character.", MinimumLength = 4)]
        public string PROJECT { get; set; }
        [Required(ErrorMessage = "Please enter project definition!")]
        [StringLength(100, ErrorMessage = "Please only enter 4-100 length character.", MinimumLength = 4)]
        public string DEFINITION { get; set; }
        [Required(ErrorMessage = "Please enter project url!")]
        [StringLength(200, ErrorMessage = "Please only enter 4-200 length character.", MinimumLength = 4)]
        public string IMAGEURL { get; set; }
        [Required(ErrorMessage = "Please enter image url!")]
        [StringLength(200, ErrorMessage = "Please only enter 4-200 length character.", MinimumLength = 4)]
        public string PROJECTURL { get; set; }
    }
}
