//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int ID { get; set; }
        public string PROJECT { get; set; }
        public string DEFINITION { get; set; }
        public string IMAGEURL { get; set; }
        public string PROJECTURL { get; set; }
    }
}
