//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SocialMedia
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Please enter social media name!")]
        [StringLength(20, ErrorMessage = "Please only enter 4-20 length character.", MinimumLength = 4)]
        public string Media { get; set; }
        [Required(ErrorMessage = "Please enter social media link!")]
        [StringLength(200, ErrorMessage = "Please only enter 4-200 length character.", MinimumLength = 4)]
        public string Link { get; set; }
        [Required(ErrorMessage = "Please enter icon!")]
        [StringLength(20, ErrorMessage = "Please only enter 1-20 length character.", MinimumLength = 1)]
        public string İcon { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
